os: Visual Studio 2019

environment:
  HOME: "%HOMEDRIVE%%HOMEPATH%"
  PYTHON: C:\Python27
  SCONS_CACHE: "%HOME%\\scons_cache"
  matrix:
    - VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      LM_PLATFORM: windows
      TOOLS: yes
      TARGET: release
      ARCH: amd64

cache:
  - "%SCONS_CACHE%"

install:
  - SET "PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - easy_install scons
  - if defined VS call "%VS%" %ARCH% # if defined - so we can also use mingw

before_build:
  - echo %PLATFORM%
  - python --version
  - scons --version
  - mkdir build
  - mkdir install

build_script:
  - scons platform=%LM_PLATFORM% target=%TARGET% tools=%TOOLS% progress=no
