language: c

before_script:
    - mkdir build
    - mkdir install

matrix:
    include:
        - os: osx
          osx_image: xcode8
          before_install: easy_install scons
          script: "scons platform=osx bits=64 target=release"

        - os: linux
          script: "scons platform=linux bits=64 target=release"
          addons:
              apt:
                  packages:
                      - scons
                  update: true

deploy:
  provider: releases
  file_glob: true
  skip_cleanup: true
  api_key:
    secure: "fff3a642dfab37f6d5055fcd84371582c305ae46"
  file:
    - "build/*.dll"
    - "build/*.so"
    - "build/*.dylib"
  on:
    repo: Shfty/libmap
    draft: true
