language: c

before_install:
    - mkdir build
    - mkdir install

matrix:
    include:
        - os: osx
          osx_image: xcode8
          before_install: brew install scons
          script: "scons platform=osx bits=64 target=release"

        - os: linux
          script: "scons platform=linux bits=64 target=release"
          addons:
              apt:
                  packages:
                      - scons
                  update: true
